### ISSUE TITLE
TFM fixes

### ISSUE THREAD

**Issue by amichai-bd** [amichai-bd/fpga_mafia_wiki#18]
Please remove the hw simulator & tools as a stand-alone sidebar 
![image](https://github.com/amichai-bd/fpga_mafia_wiki/assets/81047407/464507b9-4cbb-4d78-8386-d123d1bb2659)

**Comment by roman012285** [comment]
Will be done today

בתאריך יום ד׳, 20 בספט׳ 2023, 18:50, מאת Amichai Ben-David ‏<
***@***.***>:

**Comment by amichai-bd** [comment]
I see this was already fixed..
As an exercise, try and find the PR/commit and link it to this issue.
+ Close the issue if done

**Comment by roman012285** [comment]
Fixed. Error description in PR#17

https://github.com/amichai-bd/fpga_mafia_wiki/pull/17#issuecomment-1727920071
