### ISSUE TITLE
Using the Past Image extension - updating the setting.json

### ISSUE THREAD

**Issue by amichai-bd** [amichai-bd/fpga_mafia_wiki#26]
Found these setting to solve the issues i had 
```json
    "pasteImage.path": "${projectRoot}/static/snapshots",
    "pasteImage.basePath": "${projectRoot}/static",
    "pasteImage.prefix": "/",
    "pasteImage.insertPattern": "![${imageFileName}](${imageFilePath})",
``` 
 

Just FYI - this really speeds up the process of painting images into the markdown documentation in docusroud wiki.

@roman012285 please add this to the extension section - this is nice info to add there

**Comment by roman012285** [comment]
Thanks, I have played with it today and also added them to json file. I see that the second line seems to be allitle differente than mine and maybe this will solve an issue I had. 
PASTE IMAGE Extension put the picture to /static/snapshot as supposed to be but docosaurus compiled it as its PATH is  /static/static/snapshot so I had to remove one /static manualy from the PATH, I try this.

**Comment by roman012285** [comment]
1. issue in the previous commit is solved
2. I have added the extension to extension section
