### ISSUE TITLE
issues with creating link to page

### ISSUE THREAD

**Issue by roman012285** [amichai-bd/fpga_mafia_wiki#29]
in /docs/buid_script/intro.md in line 7 "MAFIA HOME PAGE" suppose to be a link, I tried many different PATH but docusaurus wasn't able to find the file.
In #PR28 at that point Its written **not as a link** and I will fix it after I understand how to fix the issue.
This is the link  [MAFIA HOME PAGE](../../src/pages/HomePage_content.mdx)

**Comment by amichai-bd** [comment]
I also don't know how this is done yet.
We can review this together next meeting

**Comment by roman012285** [comment]
I will continue trying it.
