### ISSUE TITLE
Using waveform for documentation - vscode extention

### ISSUE THREAD

**Issue by amichai-bd** [amichai-bd/fpga_mafia_wiki#33]
https://marketplace.visualstudio.com/items?itemName=nopeslide.vscode-drawio-plugin-
or this extension:
https://marketplace.visualstudio.com/items?itemName=bmpenuelas.waveform-render
wavedrom

Please install this to create waves for documentation.
- Save images manually (screen shot)
- save "source code" of wave in the designated directory (static/waveform)

see example:
```json
{
  "signal": [
    {"name": "clk", "wave": "p..........."},
    {"name": "core2cache_req.valid", "wave": "0101.....0.."},
    {"name": "core2cache_req.opcode", "wave": "x3x4.....x..", "data": ["read", "write", "write", "write", "write", "write"]},
    {"name": "core2cache_req.address", "wave": "x3x4.....x..", "data": ["0x05", "0x08", "0x08", "0x08", "0x08", "0x08"]},
    {"name": "core2cache_req.data", "wave": "xxx4.....x..", "data": ["0xA8", "0xA8", "0xA8", "0xA8", "0xA8"]},
    {"name": "core2cache_req.reg_id", "wave": "x3xxxxxxx..."},
    {"name": "cache_ready", "wave": "1.0.....1..."}
  ]
}
```

![image](https://github.com/amichai-bd/fpga_mafia_wiki/assets/81047407/fb5db45d-ecf2-4472-96bc-04bd8ef8ad12)

**Comment by roman012285** [comment]
sure, I installed it now. I write small explanation in extension.md

‫בתאריך יום ה׳, 28 בספט׳ 2023 ב-12:54 מאת ‪Amichai Ben-David‬‏ <‪
***@***.***‬‏>:‬

**Comment by roman012285** [comment]
Done!
